### ISSUE TITLE
[init] 타이포그래피 및 디자인 시스템 기초세팅

### ISSUE THREAD

**Issue by HAJIEUN02** [algo-hackthon/algo-client#3]
## 🛠️ ISSUE
-  타이포그래피 및 디자인 시스템 기초세팅을 진행합니다.

## 📑 To-Do
- [ ] text_appearance.xml 스타일 지정
- [ ] .otf 파일 넣기
- [ ]  colors.xml  스타일 지정
- [ ] 아이콘 추가
- [ ] 버튼 스타일 지정
